### PR TITLE
feat(logic): Implement isSparseArray

### PR DESCRIPTION
**Pull request by dawehner**
Implements https://github.com/char0n/ramda-adjunct/issues/785

Note: Initially I used Ramda.contains but Ramda.contains(undefined) doesn't find empty elements.

If you have any additional questions please don't hesitate to contact any of the core commiters.

### CODE REVIEW

**Comment by char0n** [comment]
Thanks! I'll have a look at this during today.

**Comment by char0n** [comment]
@dawehner are you still interested in finishing this, or should I take over ?

**Comment by dawehner** [comment]
Hi. I'm a bit busy right now, so I can't promise anything. Feel free to
take over :)

**Comment by char0n** [comment]
As agreed, closing in favor of https://github.com/char0n/ramda-adjunct/pull/1048

**Pull request closed without merging**
