### PR TITLE
test(files): Use chai directly instead of internal eq function in test asserts, B#20

### PR DESCRIPTION
**Pull request by js636f**
Batch 20
test/
- sliceTo.js
- spreadPath.js
- spreadProp.js
- stubArray.js
- stubNull.js
- stubObj.js
- stubString.js

### CODE REVIEW

**Comment by js636f** [comment]
Yes, we are close to the finish :-)

**Comment by char0n** [comment]
@js636f when you finish this issue and you'll be interested, I'd like to make a permanent contributor to this project. You will be mentioned in package.json as core contributor and on github. You provided great value to this project and consistently providing a value to this project is the only requirement to become contributor. There is lot of work in this repo and I have grand plans for it also ;]

**Comment by js636f** [comment]
Thank you! it would be great! I hope I'll be able to do something useful for this project.

**Comment by char0n** [comment]
What you did already is o tremendous value. I wanted to that for a year, but couldn't find time. I have a next task for you already, when you finish with `eq` function. Let's see if you like it or not ;]

**Comment by js636f** [comment]
OK :-)

**Pull request merged**
