### PR TITLE
fix: RA.defaults not exported

### LINKED ISSUE #338: defaults alias for mergeRight not exported

### PR DESCRIPTION
**Pull request by guillaumearm**
Closes #338

### CODE REVIEW

**Comment by char0n** [comment]
After reviewing this, I found out that what are we trying to do here is not correct. `defaults` should be alias of `R.merge` not `RA.mergeRight`. See [here](https://github.com/lodash/lodash/wiki/FP-Guide#installation) for reasoning.

So I suggest to revert back to original state (not export it) and remove it from [here](https://github.com/char0n/ramda-adjunct/blob/master/src/mergeRight.js#L10)

**Comment by guillaumearm** [comment]
do we choose to **remove `RA.defaults`** ?
There are signature types in `src/index.d.ts`

**Comment by char0n** [comment]
Yes, good point, I forgot about that. Remove that pls. Would not consider this breaking change as changing the major version of release because it got lost some time ago from the API and we did not even notice.

**Comment by guillaumearm** [comment]
Done.
but I need to understand something, why don't expose `RA.defaults` as `R.merge` alias ?

**Comment by char0n** [comment]
I guess because it's not part of RA itself. I think adding aliases directly for ramda functions isn't something we want to do. Adding it to direct RA functions makes sense though.

You can alias ramda itself by providing a PR to it or using syntaxes during import phase that allows this.

```js
const { merge: defaults } = require('ramda');
import { merge as defaults } from 'ramda';

**Pull request merged**
