### PR TITLE
Update signature

### LINKED ISSUE #1707: Fix invokeArgs typings
Current signature is
```ts
invokeArgs(pathToMethod: string[], args: Array<string | number>, obj: object): any;
```
but should be
```ts
invokeArgs(pathToMethod: string[], args: Array<any>, obj: object): any;
```

### PR DESCRIPTION
**Pull request by qaz6209031**
# Pull request template

Fix #1707

### CODE REVIEW

**Review by char0n — CHANGES_REQUESTED** [review]
All the signatures needs to be changed, not just two of them

**Comment by char0n** [comment]
It also seems that typing tests are not passing. after the change. Please checkout the [CI failures](https://app.circleci.com/pipelines/github/char0n/ramda-adjunct/1045/workflows/9c3b12fc-6e92-4ffa-8cd5-b4180359d91a/jobs/22369)

**Comment by qaz6209031** [comment]
Thanks for pointing out, I will try to resolve it

**Comment by char0n** [comment]
Np, thanks for working on this!

**Comment by qaz6209031** [comment]
Are there any more bugs I need to resoluve in this issue?

**Review by char0n — APPROVED** [review]
Thanks!

**Pull request merged**
