### PR TITLE
test: add ramda placeholder and make tests consistent

### PR DESCRIPTION
**Pull request by js636f**
Batch 11

Files:
test/
- isTrue.js
- isTruthy.js
- isUndefined.js
- isValidDate.js
- isValidNumber.js

src/
- isTruthy.js

### CODE REVIEW

**Comment by js636f** [comment]
Are we still waiting for another approval or I may merge this PR already?

**Comment by char0n** [comment]
Alex what do you mean by another aprroval? This is goog to go, it has
aleady been approved

**Comment by js636f** [comment]
OK. I asked about it because It's '1 pending reviewer' in 'Changes approved' section. I'm merging it.

**Comment by char0n** [comment]
@js636f hm, not sure how that happened. Sorry

**Pull request merged**
