### PR TITLE
feature (trace): minimal working example

### PR DESCRIPTION
**Pull request by BjornMelgaard**

### CODE REVIEW

**Comment by char0n** [comment]
@BjornMelgaard, please next time create a new issue describing a feature before creating a PR so that we can collaborate on it. 

I am sorry, but I am not going to merge this PR from the following reasons:

 - idea of `trace` has been already considered and rejected. It is part of #99 in it's [simple form](https://github.com/tommmyy/ramda-extension/tree/master/src)
 - it is too specific even for ramda-adjunct
 - it doesn't implement [Dependancy Inversion Principle](https://en.wikipedia.org/wiki/Dependency_inversion_principle) and it's not composable with any external logging mechanism
 - it directly contains [side effects](https://en.wikipedia.org/wiki/Side_effect_%28computer_science%29) which should not be part of any functional library
 - it can be easily be done using `tap` operator composition

```javascript
 const logging = R.curryN(2, console.dir);

 const performComplexCalc = R.compose(
   R.tap(logging('after')),
   R.subtract(__, 2),
   R.divide(__, 4),
   RA.trace('middle'),
   R.multiply(10),
   R.add(10),
   R.tap(logging('before'))
);
```

**Comment by BjornMelgaard** [comment]
Fine, took it out [here](https://github.com/BjornMelgaard/ramda-universal-trace)

**Comment by char0n** [comment]
@BjornMelgaard sorry ;[

**Comment by BjornMelgaard** [comment]
@char0n  no worries)

**Comment by tommmyy** [comment]
@BjornMelgaard If you don´t agree with @char0n , you can still use `trace`, from [ramda-extension](https://github.com/tommmyy/ramda-extension) . Our library is modular and we are focused on pretty codebase.

**Comment by BjornMelgaard** [comment]
@tommmyy tnx, noted

**Comment by guillaumearm** [comment]
There exist a [ramda-debug](https://github.com/sebinsua/ramda-debug) npm package.
I never used it, but it seems very useful.

**Pull request closed without merging**
