### PR TITLE
chore(prettier): integrate prettier with eslint and property configur…

### PR DESCRIPTION
**Pull request by char0n**
Ref #387

### CODE REVIEW

**Comment by char0n** [comment]
Codeclime is having issues for sure...

**Comment by guillaumearm** [comment]
revert and try my fix in #387

**Comment by guillaumearm** [comment]
Maybe use the `prettier/prettier` rule instead of `prettier/recommended` preset fix the issue for codeclimate.

**Comment by guillaumearm** [comment]
I just found related issue on codeclimate/codeclimate-eslint#359.
What is the version of eslint on codeclimate platform ?

**Comment by Undistraction** [comment]
@guillaumearm I don't think the version is the problem. Code Climate whitelist eslint plugins for security reasons, so sometimes a plugin will error because they don't allow it. This happened with the Ramda plugin, but I requested they add it and they did so within a few days. I think this is more likely to be the issue.

**Comment by char0n** [comment]
> You need to re-add the prettier preset (in extends) to enable eslint-config-prettier
Should I act on this ? IMHO it makes no difference

**Comment by Undistraction** [comment]
@char0n Yes. Because that is setting `prettier/prettier` to error which is what will fail the `eslint` linting.

**Comment by Undistraction** [comment]
@char0n No.

```
{
  "extends": [
    "plugin:prettier/recommended"
  ]
}
This does three things:

Enables eslint-plugin-prettier.
Sets the prettier/prettier rule to "error".
Extends the eslint-config-prettier configuration.
```

**Comment by guillaumearm** [comment]
@Undistraction : I ask for the version because [eslint#9771](https://github.com/eslint/eslint/issues/9771) and [eslint#9767](https://github.com/eslint/eslint/issues/9771)

@char0n : yes, `plugin:prettier/recommended` turns on `plugin` and `config` (Ref https://prettier.io/docs/en/eslint.html#why-not-both)

**Comment by Undistraction** [comment]
@guillaumearm From our `codeclimate.yaml`:

```
  eslint:
    enabled: true
    channel: "eslint-4"
```

**Comment by char0n** [comment]
@Undistraction, @guillaumearm so the answer to my question is NO, the PR contains proper configuration ? ;]

**Comment by guillaumearm** [comment]
@char0n : you should try, maybe we can bypass the codeclimate issue.

**Comment by char0n** [comment]
Done

**Comment by char0n** [comment]
Codeclimate ishappy now

**Comment by guillaumearm** [comment]
I think this close #379

**Comment by Undistraction** [comment]
@char0n Well done.

**Comment by char0n** [comment]
yes and #387. Now we can build abstractions like hooks and other mechanism. We have a solid base of linting + lint:fixing that we all understand. Thanks a lot for helping on this!

**Comment by guillaumearm** [comment]
Yes, git hooks is another deal, don't worry about that, we will continue to discuss about that, kindly ^^

**Comment by char0n** [comment]
I have to go to sleep. If somebody is still up after tests are complete can you pls Squash and merge this with..
```
chore(eslint): integrate prettier as eslint rule

Closes #387, #379
```

Thanks

**Comment by Undistraction** [comment]
@char0n I'll wait up.

**Pull request merged**
