### PR TITLE
fix(iterable): Convert isIterable into a type guard function

### LINKED ISSUE #1412: [Regression] Changes to isIterable breaks type safety
**Describe the bug**
[This change](https://github.com/char0n/ramda-adjunct/commit/e7b35e58ba597ef2ff98fa022fadd467b2c5ab09#diff-88bec6beae84369c0376b56b3bb88fe1L52) causes compilation errors

**To Reproduce**
```
export function foo<T>(value: T | Iterable<T>): T {
  if (isIterable(value)) {
    return value[Symbol.iterator]().next()?.value;
  }

  return value;
}
```

**Expected behavior**
Should compile.

**Actual behavior**
Fails to compile since isIterable is not a type guard function. Replacing `Iterable<T>` with `T[]` and `isIterable(value)` with `isArray(value)` would make this sample compile, though would defeat the purpose of using `isIterable`.

### PR DESCRIPTION
**Pull request by kawazoe**
Fixes #1412

### CODE REVIEW

**Comment by kawazoe** [comment]
@char0n I'm not too sure why the firefox build is broken, but the types test seems to be passing on the chrome build and cannot really have any impact on different browsers.

**Comment by char0n** [comment]
@kawazoe flaky infra of CricleCI for browser tests. I'll run them again, no worries.

Looks like you change is fine with `dstlint` for now.

**Comment by kawazoe** [comment]
Actually, I noticed that there isn't any typing test for isIterable. I'll add some before we merge this PR.

**Comment by char0n** [comment]
Thank you!

**Pull request merged**
