### PR TITLE
test: add ramda placeholder and make tests consistent

### PR DESCRIPTION
**Pull request by js636f**
Batch 17

Files:
test/
- mapIndexed.js

### CODE REVIEW

**Comment by js636f** [comment]
@char0n, may you please rerun the tests? test_node_12 failed. mapIndexed tests look good, a system error, I think.

**Comment by char0n** [comment]
@js636f rerunning

**Comment by char0n** [comment]
Re-runned again. Finally it passes.

**Comment by js636f** [comment]
Thank you!

**Pull request merged**
