### PR TITLE
style: enable eslint rule for ramda both vs either

### LINKED ISSUE #438: Enable prefer-both-either ramda linting rule
`prefer-both-either` has been [added](https://github.com/ramda/eslint-plugin-ramda/commit/6e5879be4c24a903ab57587af14f90e2746f1212) to eslint-plugin-ramda and should be enabled.

### PR DESCRIPTION
**Pull request by Undistraction**
Enables eslint-plugin-ramda linting rule to flag use of `RA.any` with only two args for replacement with `RA.either`.

Closes #438

### CODE REVIEW

**Comment by Undistraction** [comment]
Looks like Code Climate haven't updated to the latest version of `eslint-plugin-ramda`.

**Comment by char0n** [comment]
Let's keep this open then and w8 for them to update. Nice job

**Comment by Undistraction** [comment]
Requested update [here](https://github.com/codeclimate/codeclimate/issues/819)

**Comment by guillaumearm** [comment]
Maybe a dumb question but why do we enable eslint in codeclimate while we have a circleci job for that ? what is the point ?

**Comment by Undistraction** [comment]
That is a very good question.

**Comment by guillaumearm** [comment]
IMHO, we can just disable eslint in codeclimate and move on.

@char0n, any suggestions ?

**Comment by char0n** [comment]
If it's possible, let's do that. We need codeclimate to expose complexity problems and things like that.

**Comment by guillaumearm** [comment]
Yes I think it's possible.

@Undistraction : try to modifiy `.codeclimate.yml` like this : 

```yml
engines:
  eslint:
    enabled: false
```

**Pull request merged**
