### PR TITLE
test(files): add ramda placeholder and make tests consitent, B0

### PR DESCRIPTION
**Pull request by js636f**
Ref #624
Batch 0
test/isNotNull.js

### CODE REVIEW

**Comment by js636f** [comment]
@char0n, as far as I understand now I can merge approved and successfully tested commits. What button should I use, "Squash and merge" or "Rebase and merge"?

**Comment by char0n** [comment]
The rule that I'm using is this:

Does the PR needs to be squashed into one commit before merge ? - Use squash and merge
Does the PR needs the amendment of the commit message ? - Use squash and merge
No need to do anything ?  - Rebase

Regarding this PR, we need to make your commit message a little bit better:

```
test(IsNotNull): add ramda placeholder and make tests consitent (#1201)

Ref #624
```

The Ref is part of commit message, commit message contains proper subject and unnecessary wording has been removed. Pls try to adhere to those rules. They are documented in details in `CONTRIBUTING.md` or see previous PRs regarding #624

**Comment by js636f** [comment]
@char0n, OK, thank you. I read CONTRIBUTING.md, but perhaps I missed something. I'll try to make new commits messages better and now I'm using 'Squash and merge'.

**Comment by char0n** [comment]
No worries, It's just conventions you need to be familiar with and it's my job to expose them to you ;]

**Comment by js636f** [comment]
Thank you! It seems to me I successfully squashed and merged it.

**Comment by char0n** [comment]
Yes, you did. Congratulations! ;]

**Comment by js636f** [comment]
Thank you very much!

**Pull request merged**
