### PR TITLE
test(files): Use chai directly instead of internal eq function in test asserts, B#21

### PR DESCRIPTION
**Pull request by js636f**
Batch 21

test/
- stubUndefined.js
- subtractNum.js
- trimEnd.js
- trimStart.js
- trunc.js
- viewOr.js
- weave.js
- weaveLazy.js
- Y.js

### CODE REVIEW

**Comment by char0n** [comment]
is it the last one ?

**Comment by js636f** [comment]
Yes, this is the last one. As I wrote, all files in the main folder are ready.

**Comment by js636f** [comment]
Do I need to refactor tests in test/fantasy-land/ and test/internal/?

**Comment by char0n** [comment]
Yep `internal` and `fantasy-land` are required also. The goal is to delete the `eq` function from the codebase.

**Comment by js636f** [comment]
OK, I'll refactor that files too.

**Pull request merged**
