### PR TITLE
feat: add allP

### PR DESCRIPTION
**Pull request by char0n**
Ref #35

### CODE REVIEW

**Comment by char0n** [comment]
@BjornMelgaard can you have a look at this ? Thanks

**Comment by Undistraction** [comment]
Looks good to me. But unclear what `fail-fash` means - test/allP.js:44.

Also maybe add a test with two `RA.rejectP`s, verifying the first rejection message is used.

**Comment by char0n** [comment]
@Undistraction, @BjornMelgaard thanks, all comments addressed.

**Comment by Undistraction** [comment]
Nice work.

**Pull request merged**
