### PR TITLE
test(isNotNumber): add ramda placeholder and make tests consistent

### PR DESCRIPTION
**Pull request by js636f**

### CODE REVIEW

**Comment by char0n** [comment]
This PR is candidate for Squash and Merge as you have more commits you want to squash into one.

**Comment by js636f** [comment]
OK, thank you!

**Comment by char0n** [comment]
While sqash and merge you have ability to edit commit message. Pls use this ability to make commit messages easy to read. In this sqash and merge you did not edited the message and it ended up in not very readable commit message body: https://github.com/char0n/ramda-adjunct/commit/510becb7f2ff392bd04b486500aa3fdc3d66d3d7

**Comment by js636f** [comment]
OK. So, should the commit message look like this?

```
test(isNotNumber): add ramda placeholder and make tests consistent

Ref #624
```

**Comment by char0n** [comment]
Yup, exactly, the Sqash and Merge gives you possibility directly on github to create nice commit message from previous ugly multiple ugly messages ;]

**Comment by js636f** [comment]
OK, thank you!

**Pull request merged**
