### PR TITLE
test(isNotObj): add ramda placeholder and make tests consitent

### PR DESCRIPTION
**Pull request by js636f**
Ref #624

### CODE REVIEW

**Comment by js636f** [comment]
@char0n, this PR is non ready yet. As I said in the comments,   we have a bug here. RA.isNotObj(R.__) returns false. I think the problem is in src/isObj.js because src/isNotObj.js is a complement(isObj) and RA.isObj(R.__) just returns true, so I think we need to refactor src/isObj.js to eliminate the bug. Do you have any ideas about possible refactoring?

**Comment by char0n** [comment]
Implementing currying support for `isObj` should resolve it:

```js
import curry1 from 'ramda/src/internal/_curry1';

const isObj = curry1(both(isNotNull, either(isOfTypeObject, isFunction)));

**Comment by js636f** [comment]
OK, thank you!

**Comment by js636f** [comment]
Thank you!

**Pull request merged**
