### PR TITLE
refactor(isArray): use Array.isArray if available

### LINKED ISSUE #211: isArray
Use Array.isArray under the hood, otherwise fallback to ramda.

### PR DESCRIPTION
**Pull request by char0n**
Closes #211

### CODE REVIEW

**Comment by char0n** [comment]
@BjornMelgaard CR pls

**Comment by char0n** [comment]
We now have native way in ES6 to check if something is array with `Array.isArray`. This PR uses this ES6 feature if available, if not it falls-back to ramda array checking.

**Comment by BjornMelgaard** [comment]
I wonder how it works with [`or`](https://github.com/ramda/ramda/blob/v0.25.0/source/or.js)? Isn't it must use [`either`](https://github.com/ramda/ramda/blob/v0.25.0/source/either.js)?

**Comment by char0n** [comment]
Nope, `either` is higher order function, `or` is boolean switch. So the code can be rewritten to:
```javascript
const isArray = Array.isArray || _isArray;
```
or 
```javascript
const isArray = (val) => {
  if (isFunction(Array.isArray)) { 
    return Array.isArray(val);
  }
  return _isArray(val);
}
```

**Comment by BjornMelgaard** [comment]
@char0n this what I mean too
Isn't `Array.isArray || _isArray;` just checks presence of `Array.isArray` or `_isArray`

**Comment by char0n** [comment]
So is it clear now ? Shall we go for the merge ?

**Comment by BjornMelgaard** [comment]
@char0n yes, its clear now

```js
const isArray = Array.isArray || _isArray;
```

is more like

```js
let isArray
if(Array.isArray) {
  isArray = Array.isArray
else {
  isArray = _isArray
}
```

sorry, can merge now

**Pull request merged**
