### PR TITLE
improve renameKeys type

### PR DESCRIPTION
**Pull request by mendrik**
Improves upon the `object` type in renameKeys. Not sure if this can be merged as is, but maybe it can be extended by someone who knows the project better than me

### CODE REVIEW

**Comment by char0n** [comment]
Hi @mendrik, 

Thanks for contributing. Would you be able to provide a test as well? See here how tests are done: https://github.com/char0n/ramda-adjunct/tree/master/test

**Comment by mendrik** [comment]
> Hi @mendrik,
> 
> Thanks for contributing. Would you be able to provide a test as well? See here how tests are done: https://github.com/char0n/ramda-adjunct/tree/master/test

sorry if I misunderstand something, but the tests are testing the functionality while I have only improved upon the typescript types. Is there a way to test the typescript types for validity?

**Comment by char0n** [comment]
Hi @mendrik,

Sorry, wrong url. Here is the right location: https://github.com/char0n/ramda-adjunct/tree/master/types/test

**Comment by mendrik** [comment]
ok I got stuck with this I tried to make a test like so
```
import * as RA from 'ramda-adjunct';

RA.renameKeys({ A: 'B'} as const, { A: 1, B: 4 }).B; // $ExpectType number
```
but then different things start to complain, seems that dtstype checker isn't the most versatile tool.

**Comment by mendrik** [comment]
ok so I got stuck with this:
```
import * as RA from 'ramda-adjunct';

RA.renameKeys({ A: 'B'} as const, { A: 1, C: 4 }).B; // $ExpectType number
```

doesn't seem to work

**Comment by char0n** [comment]
> ok so I got stuck with this:
> 
> ```
> import * as RA from 'ramda-adjunct';
> 
> RA.renameKeys({ A: 'B'} as const, { A: 1, C: 4 }).B; // $ExpectType number
> ```
> 
> doesn't seem to work

I've issued a PR that should remedy your issue: https://github.com/char0n/ramda-adjunct/pull/2368. Rebase on top of the `master` branch and things should work as expected again.

**Comment by mendrik** [comment]
closing, sorry it is constantly misbehaving for me in the tests, even after rebasing. 
image

**Comment by char0n** [comment]
@mendrik,

Sorry for your trouble. I was able to successfully incorporate your change into the codebase in https://github.com/char0n/ramda-adjunct/pull/2370. I've properly attributed you in the commit.

Again sorry for the trouble and thanks for contributing!

**Comment by mendrik** [comment]
> @mendrik,
> 
> Sorry for your trouble. I was able to successfully incorporate your change into the codebase in #2370. I've properly attributed you in the commit.
> 
> Again sorry for the trouble and thanks for contributing!

awesome, thanks a bunch for not letting it go to waste! :)

**Pull request closed without merging**
